import { Inter } from "next/font/google";

import "../public/assets/css/main.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel='stylesheet' href='assets/css/bootstrap.css' />
        <link rel='stylesheet' href='assets/css/animate.css' />
        <link rel='stylesheet' href='assets/css/swiper-bundle.css' />
        <link rel='stylesheet' href='assets/css/slick.css' />
        <link rel='stylesheet' href='assets/css/magnific-popup.css' />
        <link rel='stylesheet' href='assets/css/font-awesome-pro.css' />
        <link rel='stylesheet' href='assets/css/spacing.css' />
        <link rel='stylesheet' href='assets/css/custom-animation.css' />
      </head>
      <body className={inter.className} id='body'>
        <div>{children}</div>
        <Script src='assets/js/vendor/jquery.js'></Script>
        <Script src='assets/js/bootstrap-bundle.js'></Script>
        <Script src='assets/js/gsap.js'></Script>
        <Script src='assets/js/gsap-scroll-to-plugin.js'></Script>
        <Script src='assets/js/gsap-scroll-smoother.js'></Script>
        <Script src='assets/js/gsap-scroll-trigger.js'></Script>
        <Script src='assets/js/gsap-split-text.js'></Script>
        <Script src='assets/js/chroma.min.js'></Script>
        <Script src='assets/js/three.js'></Script>
        <Script src='assets/js/tween-max.js'></Script>
        <Script src='assets/js/scroll-magic.js'></Script>
        <Script src='assets/js/range-slider.js'></Script>
        <Script src='assets/js/swiper-bundle.js'></Script>
        <Script src='assets/js/slick.js'></Script>
        <Script src='assets/js/magnific-popup.js'></Script>
        <Script src='assets/js/nice-select.js'></Script>
        <Script src='assets/js/purecounter.js'></Script>
        <Script src='assets/js/beforeafter.js'></Script>
        <Script src='assets/js/isotope-pkgd.js'></Script>
        <Script src='assets/js/imagesloaded-pkgd.js'></Script>
        {/* <Script src='assets/js/ajax-form.js'></Script> */}
        <Script src='assets/js/webgl.js'></Script>
        <Script src='assets/js/main.js'></Script>
        <Script src='assets/js/tp-cursor.js'></Script>
      </body>
    </html>
  );
}
